#!/bin/sh
COMMIT_MSG_FILE=$1
FIRST_LINE=$(head -1 "$COMMIT_MSG_FILE")

PATTERN='^(feat|fix|docs|style|refactor|perf|test|build|ci|chore)\(NSP-[0-9]{1,5}\)!?: .+$'
MAX_LENGTH=72 #(22+50)

# Validate commit message format
if ! echo "$FIRST_LINE" | grep -qE "$PATTERN"; then
  echo "Error: Commit message does not follow the required format." >&2
  echo "Correct format: type(NSP-12345): description" >&2
  exit 1
fi

# Validate commit message length
if [ ${#FIRST_LINE} -gt $MAX_LENGTH ]; then
  echo "Error: The commit message summary (first line) is longer than $MAX_LENGTH characters." >&2
  exit 1
fi

exit 0

